[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["MetarixStaking_V1"]

optimizer = true
optimizer_runs = 100_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config